### ISSUE TITLE
How to build the application yourself?

### ISSUE THREAD

**Issue by Sjoerdtvanvliet** [BouweCeunen/computer-vision-jetson-nano#3]
Hello,

I tried to build the image of your application myself. However I'm still new to docker and ran in some trouble. I just want to modify your vision.py to work on my type of camera, however I runned into some issues. Currently already three full days banging my head to get this to work. First the debians file should not be placed like described in the resources folder but in the debs folder if I look at your move.xxxxxx.sh file. If you open it you can see that it does not move from the resources folder but the deb folder. Got that working, but now I should start building the image/appication/container. Being new to docker gives me here a big disadvantage, because you don't have like a walktrough to do this. However is there like a main dockerfile I can run that automatically installs/calls the other dockerfiles of  the sub-directories cuda, cudnn, opencv, python, enz? Because building each dockerfile in these maps separately takes more space than available on my nano. Could you give me tips/help how to set this up? Thanks in advance for your time to help me.

Best regards,

Sjoerd

**Comment by BouweCeunen** [comment]
Hi Sjoerd,

Indeed, the `resources` folder is mainly a directory for scripts. I correct the typo.

You should be able to build each dockerfile independently if you want to starting from `l4t`. They all build on top of one another. The last one is located in the `vision` folder. You can only build the last one if you want to, all other docker containers are already on Docker Hub, so each one can build from the images on there. Hope this helps a bit.

**Comment by Sjoerdtvanvliet** [comment]
Hi Bouwe,

Thank you for your quick reaction. You say start from l4t and end with the vision folder. However what is the seqeuence between these folders l4t --> cuda -->cudnn --> ... --> vision? Is it after l4t alphabetical? Does the order matter? Could you explain the exact sequence?

Best regards,

Sjoerd

**Comment by BouweCeunen** [comment]
The `l4t (Linux4Tegra)` is the first one, it starts from a Balena docker image made for the Jetson. If you look at the Dockerfile of `cuda` you'll see that it starts from `l4t` (FROM bouwe/jetson-nano-l4t:latest). The `cudnn` container starts from the `cuda` container and so on. You can follow the sequence by looking at the Dockerfiles.

The sequence is `l4t` -> `cuda` -> `cudnn` -> `nvinfer` -> `tensorrt` -> `opencv` -> `detectnet` -> `vision`. Again, you don't need to build everything yourself, you can just start from the `vision` directory, that contains the vision.py.

**Comment by Sjoerdtvanvliet** [comment]
Thank you Bouwe. Everything is clear now, it works.
